from enum import Enum

from dcs import task
from dcs.planes import PlaneType
from dcs.weapons_data import Weapons

from game.modsupport import planemod
from pydcs_extensions.weapon_injector import inject_weapons


class WeaponsSEM:
    Fuel_Tank_1100_Liter = {
        "clsid": "{SEM1100_PTB}",
        "name": "Fuel Tank 1100 Liter",
        "weight": 1150,
    }
    Fuel_Tank_625_Liter = {
        "clsid": "{SEM625_PTB}",
        "name": "Fuel Tank 625 Liter",
        "weight": 1150,
    }


inject_weapons(WeaponsSEM)


@planemod
class VSN_SEM(PlaneType):
    id = "VSN_SEM"
    flyable = True
    height = 4
    width = 13.05
    length = 18
    fuel_max = 6103
    max_speed = 2649.996
    chaff = 90
    flare = 45
    charge_total = 180
    chaff_charge_size = 1
    flare_charge_size = 2
    category = "Interceptor"  # {78EFB7A2-FD52-4b57-A6A6-3BF0E1D6555F}
    radio_frequency = 127.5

    class Liveries:
        class USSR(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Georgia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Venezuela(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Australia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Israel(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Combined_Joint_Task_Forces_Blue(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Sudan(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Norway(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Romania(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Iran(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Ukraine(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Libya(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Belgium(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Slovakia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Greece(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class UK(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Third_Reich(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Hungary(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Abkhazia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Morocco(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class United_Nations_Peacekeepers(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Switzerland(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class SouthOssetia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Vietnam(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class China(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Yemen(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Kuwait(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Serbia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Oman(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class India(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Egypt(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class TheNetherlands(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Poland(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Syria(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Finland(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Kazakhstan(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Denmark(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Sweden(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Croatia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class CzechRepublic(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class GDR(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Yugoslavia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Bulgaria(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class SouthKorea(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Tunisia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Combined_Joint_Task_Forces_Red(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Lebanon(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Portugal(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Cuba(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Insurgents(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class SaudiArabia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class France(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class USA(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Honduras(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Qatar(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Russia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class United_Arab_Emirates(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Italian_Social_Republi(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Austria(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Bahrain(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Italy(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Chile(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Turkey(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Philippines(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Algeria(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Pakistan(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Malaysia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Indonesia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Iraq(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Germany(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class South_Africa(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Jordan(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Mexico(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class USAFAggressors(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Brazil(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Spain(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Belarus(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Canada(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class NorthKorea(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Ethiopia(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Japan(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

        class Thailand(Enum):
            ARA = "ARA"
            ARA_1 = "ARA 1"
            ARA_2 = "ARA 2"
            Aeronavale_1 = "Aeronavale 1"
            Flotille_11F_Camo_1 = "Flotille 11F Camo 1"
            Flotille_11F_Camo_2 = "Flotille 11F Camo 2"
            Flotille_11F_Grey_1 = "Flotille 11F Grey 1"
            Flotille_11F_Grey_2 = "Flotille 11F Grey 2"
            Flotille_17F_Camo = "Flotille 17F Camo"
            Flotille_17F_Grey = "Flotille 17F Grey"
            Flottille_11F = "Flottille 11F"
            Flottille_14F = "Flottille 14F"
            Flottille_17F = "Flottille 17F"
            IRAQ_Grey_1 = "IRAQ Grey 1"
            IRAQ_Grey_2 = "IRAQ Grey 2"
            IRAQ_Grey_3 = "IRAQ Grey 3"

    class Pylon1:
        Smokewinder___red = (1, Weapons.Smokewinder___red)
        Smokewinder___green = (1, Weapons.Smokewinder___green)
        Smokewinder___blue = (1, Weapons.Smokewinder___blue)
        Smokewinder___white = (1, Weapons.Smokewinder___white)
        Smokewinder___yellow = (1, Weapons.Smokewinder___yellow)
        AN_ASQ_T50_TCTS_Pod___ACMI_Pod = (1, Weapons.AN_ASQ_T50_TCTS_Pod___ACMI_Pod)
        Mk_81___250lb_GP_Bomb_LD = (1, Weapons.Mk_81___250lb_GP_Bomb_LD)
        Mk_82___500lb_GP_Bomb_LD = (1, Weapons.Mk_82___500lb_GP_Bomb_LD)
        R550_Magic_2_IR_AAM = (1, Weapons.R550_Magic_2_IR_AAM)
        LAU_61_pod___19_x_2_75_Hydra__UnGd_Rkts_M151__HE = (
            1,
            Weapons.LAU_61_pod___19_x_2_75_Hydra__UnGd_Rkts_M151__HE,
        )
        ALQ_131___ECM_Pod = (1, Weapons.ALQ_131___ECM_Pod)
        AIM_9M_Sidewinder_IR_AAM = (1, Weapons.AIM_9M_Sidewinder_IR_AAM)
        AIM_9P_Sidewinder_IR_AAM = (1, Weapons.AIM_9P_Sidewinder_IR_AAM)

    class Pylon2:
        AGM_65K___Maverick_K__CCD_Imp_ASM_ = (
            2,
            Weapons.AGM_65K___Maverick_K__CCD_Imp_ASM_,
        )
        GBU_12___500lb_Laser_Guided_Bomb = (2, Weapons.GBU_12___500lb_Laser_Guided_Bomb)
        LAU_61_pod___19_x_2_75_Hydra__UnGd_Rkts_M151__HE = (
            2,
            Weapons.LAU_61_pod___19_x_2_75_Hydra__UnGd_Rkts_M151__HE,
        )
        Mk_81___250lb_GP_Bomb_LD = (2, Weapons.Mk_81___250lb_GP_Bomb_LD)
        Mk_82___500lb_GP_Bomb_LD = (2, Weapons.Mk_82___500lb_GP_Bomb_LD)
        Fuel_Tank_1100_Liter = (2, WeaponsSEM.Fuel_Tank_1100_Liter)
        Fuel_Tank_625_Liter = (2, WeaponsSEM.Fuel_Tank_625_Liter)

    # ERRR <CLEAN>

    class Pylon5:
        L_081_Fantasmagoria_ELINT_pod = (5, Weapons.L_081_Fantasmagoria_ELINT_pod)

    class Pylon6:
        MER2_with_2_x_Mk_82___500lb_GP_Bombs_LD = (
            6,
            Weapons.MER2_with_2_x_Mk_82___500lb_GP_Bombs_LD,
        )
        AGM_65K___Maverick_K__CCD_Imp_ASM_ = (
            6,
            Weapons.AGM_65K___Maverick_K__CCD_Imp_ASM_,
        )

    # ERRR <CLEAN>

    class Pylon10:
        AGM_65K___Maverick_K__CCD_Imp_ASM_ = (
            10,
            Weapons.AGM_65K___Maverick_K__CCD_Imp_ASM_,
        )
        GBU_12___500lb_Laser_Guided_Bomb = (
            10,
            Weapons.GBU_12___500lb_Laser_Guided_Bomb,
        )
        LAU_61_pod___19_x_2_75_Hydra__UnGd_Rkts_M151__HE = (
            10,
            Weapons.LAU_61_pod___19_x_2_75_Hydra__UnGd_Rkts_M151__HE,
        )
        Mk_81___250lb_GP_Bomb_LD = (10, Weapons.Mk_81___250lb_GP_Bomb_LD)
        Mk_82___500lb_GP_Bomb_LD = (10, Weapons.Mk_82___500lb_GP_Bomb_LD)
        Fuel_Tank_1100_Liter = (10, WeaponsSEM.Fuel_Tank_1100_Liter)
        Fuel_Tank_625_Liter = (10, WeaponsSEM.Fuel_Tank_625_Liter)

    class Pylon11:
        Smokewinder___red = (11, Weapons.Smokewinder___red)
        Smokewinder___green = (11, Weapons.Smokewinder___green)
        Smokewinder___blue = (11, Weapons.Smokewinder___blue)
        Smokewinder___white = (11, Weapons.Smokewinder___white)
        Smokewinder___yellow = (11, Weapons.Smokewinder___yellow)
        AN_ASQ_T50_TCTS_Pod___ACMI_Pod = (11, Weapons.AN_ASQ_T50_TCTS_Pod___ACMI_Pod)
        Mk_81___250lb_GP_Bomb_LD = (11, Weapons.Mk_81___250lb_GP_Bomb_LD)
        Mk_82___500lb_GP_Bomb_LD = (11, Weapons.Mk_82___500lb_GP_Bomb_LD)
        R550_Magic_2_IR_AAM = (11, Weapons.R550_Magic_2_IR_AAM)
        LAU_61_pod___19_x_2_75_Hydra__UnGd_Rkts_M151__HE = (
            11,
            Weapons.LAU_61_pod___19_x_2_75_Hydra__UnGd_Rkts_M151__HE,
        )
        ALQ_131___ECM_Pod = (11, Weapons.ALQ_131___ECM_Pod)
        AIM_9M_Sidewinder_IR_AAM = (11, Weapons.AIM_9M_Sidewinder_IR_AAM)
        AIM_9P_Sidewinder_IR_AAM = (11, Weapons.AIM_9P_Sidewinder_IR_AAM)

    pylons = {1, 2, 3, 5, 6, 9, 10, 11}

    tasks = [
        task.CAP,
        task.Escort,
        task.FighterSweep,
        task.Intercept,
        task.Reconnaissance,
        task.GroundAttack,
        task.CAS,
        task.AFAC,
        task.RunwayAttack,
    ]
    task_default = task.FighterSweep
